---
abstract: 'An AnyEvent compatible module to monitor files/directories for changes'
author:
  - 'Mark Grimes, E<lt>mgrimes@cpan.orgE<gt>'
build_requires:
  Data::Dump: 0
  Exporter: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0.87
  Test::Without::Module: 0
  autodie: 0
configure_requires:
  Module::Build: 0.35
generated_by: 'Module::Build version 0.3508'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Filesys-Notify
provides:
  AnyEvent::Filesys::Notify:
    file: lib/AnyEvent/Filesys/Notify.pm
    version: 0.04
  AnyEvent::Filesys::Notify::Event:
    file: lib/AnyEvent/Filesys/Notify/Event.pm
  AnyEvent::Filesys::Notify::Role::Fallback:
    file: lib/AnyEvent/Filesys/Notify/Role/Fallback.pm
  AnyEvent::Filesys::Notify::Role::Linux:
    file: lib/AnyEvent/Filesys/Notify/Role/Linux.pm
  AnyEvent::Filesys::Notify::Role::Mac:
    file: lib/AnyEvent/Filesys/Notify/Role/Mac.pm
requires:
  AnyEvent: 0
  Carp: 0
  Cwd: 0
  File::Find::Rule: 0
  Mac::FSEvents: 0
  Moose: 0
  Try::Tiny: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=AnyEvent-Filesys-Notify-Event
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mvgrimes/AnyEvent-Filesys-Notify
version: 0.04
